# Generated by Django 3.1.5 on 2021-01-21 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=70)),
                ('sport', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('sex', models.CharField(max_length=15)),
                ('age', models.CharField(max_length=7)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=70)),
                ('noc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_time_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoa')),
                ('id_time_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
        migrations.CreateModel(
            name='MedalhaPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medalha_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medalha')),
                ('id_pessoa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoa')),
            ],
        ),
    ]
