# Generated by Django 3.1.5 on 2021-01-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeEvento',
            new_name='PessoaEvento',
        ),
        migrations.RemoveField(
            model_name='pessoaevento',
            name='id_time_fk',
        ),
        migrations.AddField(
            model_name='pessoaevento',
            name='id_pessoa_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.pessoa'),
            preserve_default=False,
        ),
    ]
