# Generated by Django 3.1.5 on 2021-01-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210121_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoaevento',
            name='id_evento_fk',
        ),
        migrations.RemoveField(
            model_name='pessoaevento',
            name='id_pessoa_fk',
        ),
        migrations.RemoveField(
            model_name='pessoatime',
            name='id_pessoa_fk',
        ),
        migrations.RemoveField(
            model_name='pessoatime',
            name='id_time_fk',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_evento',
            field=models.ManyToManyField(to='api.Evento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_medalha',
            field=models.ManyToManyField(to='api.Medalha'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_time',
            field=models.ManyToManyField(to='api.Time'),
        ),
        migrations.DeleteModel(
            name='MedalhaPessoa',
        ),
        migrations.DeleteModel(
            name='PessoaEvento',
        ),
        migrations.DeleteModel(
            name='PessoaTime',
        ),
    ]
